theme: jekyll-theme-minimal

title: Prof. Haller Bracho
description: Mi objetivo profesional es ayudar a desarrollar herramientas visuales que sirvan de apoyo en la toma de decisiones y faciliten la solución de problemas en las organizaciones, utilizando sistemas de geometría dinámica y apoyado en algoritmos y modelos matemáticos.

show_downloads: false
